### ISSUE TITLE
GC warning / Possible memory leak

### ISSUE THREAD

**Issue by FireMasterK** [iv-org/invidious#1415]
```
GC Warning: Repeated allocation of very large block (appr. size 1052672):
        May lead to memory leak and poor performance
```

**Comment by TheFrenchGhosty** [comment]
Are you running the latest version? (from 20 minutes ago)

This kind of problem should be fixed.

**Comment by FireMasterK** [comment]
I have not, I will update and report my finding.

**Comment by FireMasterK** [comment]
It still occurs, maybe not as frequent as before I still see the warning every few minutes.

**Comment by TheFrenchGhosty** [comment]
Closed in favor of #1438
