### ISSUE TITLE
[Bug] "Invalid memory access" on Docker-compose

### ISSUE THREAD

**Issue by atropos112** [iv-org/invidious#1791]
Hello,

I am running invidious on my home server via the Docker-compose in the repository. Yesterday and day before yesterday it ran well (except some buffering issues). I have ran  
`docker-compose pull && docker-compose up --force-recreate --build && docker image prune -f`
to see if there is a update of sorts, that might resolve my buffering issue. Since then I've been getting 

```
Iinvidious_invidious_1 exited with code 11
invidious_1  | Invalid memory access (signal 11) at address 0x1
invidious_1  | [0x753656] ???
invidious_1  | [0x41e36c] ???
invidious_1  | [0x12165c9] ???
invidious_1  | [0x12354d1] ???
```
and no instance turns on. I found few issues mentioning similar problem but they mostly had great memory limitations, i have about 60 gb of ram to spare so I doubt its that. I figured it might be just bad luck in building, so i rebuilt it few times but the error is just the same.

**Comment by FireMasterK** [comment]
```
[development] Kemal is ready to lead at http://0.0.0.0:3000
Invalid memory access (signal 11) at address 0x1
[0x753656] ???
[0x41e36c] ???
[0x12165c9] ???
[0x12354d1] ???
[development] Kemal is ready to lead at http://0.0.0.0:3000
Invalid memory access (signal 11) at address 0x1
[0x753656] ???
[0x41e36c] ???
[0x12165c9] ???
[0x12354d1] ???
[development] Kemal is ready to lead at http://0.0.0.0:3000
Invalid memory access (signal 11) at address 0x1
[0x753656] ???
[0x41e36c] ???
[0x12165c9] ???
[0x12354d1] ???
[development] Kemal is ready to lead at http://0.0.0.0:3000
```

Invidious is almost crashing 3-4 times a second for me...

**Comment by LennyPenny** [comment]
to anyone that updated their docker image and now can't roll back as the IV docker image repo only has the `latest` tag. 

- Run `docker images` to list all docker images 
- Find the image id you were running before updating (should be the newest not tagged with `latest`)
- run `docker image tag <image-id> omarroth/invidious:<image-id>`
- edit your docker-compose.yml to use the tag you created
- `docker-compuse up -d`

**Comment by atropos112** [comment]
> 
> 
> to anyone that updated their docker image and now can't roll back as the IV docker image repo only has the `latest` tag.
> 
>     * Run `docker images` to list all docker images
> 
>     * Find the image id you were running before updating (should be the newest not tagged with `latest`)
> 
>     * run `docker image tag <image-id> omarroth/invidious:<image-id>`
> 
>     * edit your docker-compose.yml to use the tag you created
> 
>     * `docker-compuse up -d`
> 
> 
> (make sure to subscribe to this thread and switch back to `latest` in a few days when this hopefully has been resolved)

That is a very good idea, facepalming myself as i have pruned images away just "to be sure". Thank you for the suggestion though, will definitely use in the future.

**Comment by LennyPenny** [comment]
Nevermind, looks like the actual official place to get invidious docker images is here: https://quay.io/repository/invidious/invidious?tab=tags

**Comment by LennyPenny** [comment]
also looks like fix has been released 👍 this can closed

**Comment by Perflyst** [comment]
The bug is not fixed, I just reverted the lsquic update https://github.com/iv-org/invidious/commit/dacb1a70eee85c57e62f9e5c8057cdf372eac1d0

You can get old image versions on quay, it is not announced yet though. Dockerhub images are auto build in omarroth's account.

**Comment by atropos112** [comment]
I thought this was finished no ?

**Comment by Perflyst** [comment]
The bug still exists with the new lsquic library, we need to figure out why

**Comment by FireMasterK** [comment]
The bug needs to be fixed so that lsquic can be updated.

**Comment by atropos112** [comment]
Oh I see, my bad.

**Comment by saltycrys** [comment]
I forgot to update the Dockerfile, it downloads a specific version: https://github.com/iv-org/invidious/blob/b29e60a97aaef1d513208e177ecae8ffc671a3d9/docker/Dockerfile#L7

I'm pretty sure that line can be removed, `liblsquic.a` is tracked in the shard so it doesn't need to be downloaded separately.

After removing that line to update the `lsquic` shard:
- Update the version in `shard.yml`: https://github.com/iv-org/invidious/blob/dacb1a70eee85c57e62f9e5c8057cdf372eac1d0/shard.yml#L28-L30
- Run `shards update`
- Verify version in `shards.lock`: https://github.com/iv-org/invidious/blob/dacb1a70eee85c57e62f9e5c8057cdf372eac1d0/shard.lock#L19-L21
- Commit both `shards.yml` and `shards.lock`

**Comment by unixfox** [comment]
@saltycrys do you want us to test on our Docker setup?

**Comment by saltycrys** [comment]
Yes, that would be great. And if it works please make a PR for it.

**Comment by Rjevski** [comment]
@saltycrys I have tested your changes (removing the "manual" lsquic download and relying on `shards` to install it) which seem to now be in master and no results. Consistent invalid memory access errors, sometimes right at startup, sometimes within ~1h of runtime.

Note that this doesn't seem to be a Docker-specific issue but might be hardware-dependent. Running it in Docker in a VMware VM worked successfully for ages, but running it in the same Docker-based setup on bare-metal (on the same machine that ran VMware, so hardware is unlikely to be faulty) produces the issue.

**Comment by saltycrys** [comment]
Yes, I'm also seeing invalid memory access errors. This is a problem with the bindings, any help is much appreciated: https://github.com/iv-org/lsquic.cr

This issue was about the mismatched binary that caused Invidious to immediately crash at startup. Please open another issue for the invalid memory access errors and post all the crash logs there.
