### ISSUE TITLE
[Feature request] Support viewing all of a channel's videos in one playlist

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#3018]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to just play all of a channel's videos one after the other.

**Describe the solution you'd like**
A button like "View all" that plays a channel's videos one after another

**Describe alternatives you've considered**

**Additional context**

**Comment by TheFrenchGhosty** [comment]
Note: can be easily done since /videos is (unless it changed) considered a playlist by YouTube

**Comment by SamantazFox** [comment]
@TheFrenchGhosty nope, `/channel/<id>/videos` only lists the instance videos.

The playlist for all the videos of a channel works by replacing `UC` by `UU`.

E.g:
```
https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw
https://www.youtube.com/watch?v=RTT5k2imblA&list=UUXuqSBlHAE6Xw-yeJA0Tunw
```

**Comment by TheFrenchGhosty** [comment]
@SamantazFox So it's still possible, with UU?

**Comment by SamantazFox** [comment]
https://test.invidious.io/playlist?list=UUXuqSBlHAE6Xw-yeJA0Tunw

**Comment by TheFrenchGhosty** [comment]
@SamantazFox Great. So we just have to link to this somewhere and this issue is solved.

**Comment by SamantazFox** [comment]
@TheFrenchGhosty I'll probably do that after #2546 is rebased and merged.

**Comment by hommegithub** [comment]
> https://test.invidious.io/playlist?list=UUXuqSBlHAE6Xw-yeJA0Tunw

Sorry for hijacking - been researching on how to auto update/add subscription feeds into the customer playlist on Invidious but still can't figure out how.

Either Yattee nor Invidious support "auto play" / play all videos from feeds with iOS/tvOS so I figured the only way to achieve that is from a playlist which consist of the channels I subscribed based on newest upload.

Thanks.

**Comment by DCCXX** [comment]
UU and UC work exactly the same on Invidious, compare:
- https://test.invidious.io/playlist?list=UUXuqSBlHAE6Xw-yeJA0Tunw
- https://test.invidious.io/playlist?list=UCXuqSBlHAE6Xw-yeJA0Tunw

**Comment by j12i** [comment]
it would als be neat to have a way to play it in chronological order (not reverse)

**Comment by montvid** [comment]
any news on this? Using this in NewPipe on Android, on pc invidious can't find an alternative at the moment.
