### ISSUE TITLE
[Bug] Video descriptions sometimes don't load.

### ISSUE THREAD

**Issue by unnamed24** [iv-org/invidious#3660]
It was noticed that at random times and it is not clear from what situations, the descriptions for the video are not loaded, which leaves an empty field instead of the description.
Video example:
https://inv.odyssey346.dev/watch?v=mPypEpPB2UQ
Screenshot of what the video description field looks like at the moment:
![unnamed](https://user-images.githubusercontent.com/124290392/221259313-059f23f5-cc84-41d7-99e1-4e073b8df976.png)
However, at the same time, on YouTube, the descriptions are loaded as expected.

----

Bounties for fixing this issue:
- @LennyPenny $5: `send me a message from a mastodon account or email linked in your github profile linked to the commit once merged`
- @99thim $5: `Same as LennyPenny, happy to offer $5 too to have this fixed. Would pay with bitcoin`

**Comment by garoto** [comment]
Observing this behavior as well on four public instances and with different, popular videos.

**Comment by SamantazFox** [comment]
Youtube has changed their description format ...

Here's how it looks now:
```json
"attributedDescription": {
  "content": "Save 10% and Free Worldwide Shipping at The Ridge by using offer code WAN at https://www.ridge.com/LINUS\n\nVisit https://www.squarespace.com/WAN and use offer code WAN for 10% off\n\nJumpCloud offers an Open Directory Platform that makes it possible to unify your technology stack across identity, access, and device management. Learn more here: https://lmg.gg/JumpCloud\n\nPodcast Download: TBD\n\nTimestamps: TBD",
  "commandRuns": [
    {
      "startIndex": 77,
      "length": 27,
      "onTap": {
        "innertubeCommand": {
          "commandMetadata": {
            "webCommandMetadata": {
              "url": "https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.ridge.com%2FLINUS&v=_FqH1rqQrQg",
              "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
              "rootVe": 83769
            }
          },
          "urlEndpoint": {
            "url": "https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.ridge.com%2FLINUS&v=_FqH1rqQrQg",
            "target": "TARGET_NEW_WINDOW",
            "nofollow": true
          }
        }
      }
    },
    {
      "startIndex": 112,
      "length": 31,
      "onTap": {
        "innertubeCommand": {
          "commandMetadata": {
            "webCommandMetadata": {
              "url": "https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.squarespace.com%2FWAN&v=_FqH1rqQrQg",
              "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
              "rootVe": 83769
            }
          },
          "urlEndpoint": {
            "url": "https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.squarespace.com%2FWAN&v=_FqH1rqQrQg",
            "target": "TARGET_NEW_WINDOW",
            "nofollow": true
          }
        }
      }
    },
    {
      "startIndex": 343,
      "length": 24,
      "onTap": {
        "innertubeCommand": {
          "commandMetadata": {
            "webCommandMetadata": {
              "url": "https://www.youtube.com/redirect?q=https%3A%2F%2Flmg.gg%2FJumpCloud&v=_FqH1rqQrQg",
              "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
              "rootVe": 83769
            }
          },
          "urlEndpoint": {
            "url": "https://www.youtube.com/redirect?q=https%3A%2F%2Flmg.gg%2FJumpCloud&v=_FqH1rqQrQg",
            "target": "TARGET_NEW_WINDOW",
            "nofollow": true
          }
        }
      }
    }
  ],
  "styleRuns": [
    {
      "startIndex": 77,
      "length": 27,
      "fontColor": 4278607828
    },
    {
      "startIndex": 112,
      "length": 31,
      "fontColor": 4278607828
    },
    {
      "startIndex": 343,
      "length": 24,
      "fontColor": 4278607828
    }
  ]
}
```

**Comment by Trit34** [comment]
Another example, if needed:
https://invidious.fdn.fr/watch?v=zL-OjQtvb68 (no description at all, though there is one on the original YT page)

But it’s still working fine on other videos, like this one:
https://invidious.fdn.fr/watch?v=MEHTgCy0TJ4

**Comment by SamantazFox** [comment]
Related: https://github.com/TeamNewPipe/NewPipeExtractor/pull/953

**Comment by gardockt** [comment]
As a workaround, I made a UserScript that gets the description from `<meta>` node: https://gist.github.com/gardockt/af1243d36d8b659b98a13720b81bd9f3

**Comment by a7maadf** [comment]
> Youtube has changed their description format ...

> Here's how it looks now:

How did it look before? @SamantazFox

**Comment by Trit34** [comment]
> As a workaround, I made a UserScript that gets the description from `<meta>` node: https://gist.github.com/gardockt/af1243d36d8b659b98a13720b81bd9f3

Does not work for me (in TamperMonkey, on an instance in version 2023.03.12-cbb034f1 @ master).

**Comment by 99thim** [comment]
Script doesnt work for me either

**Comment by garoto** [comment]
For reference, the user-script by gardockt works for me using Palemoon v31.4.2 with its old, greasymonkey specific fork.

**Comment by 99thim** [comment]
With respect to gradockt's UserScript of Video Description which I have been testing and which now works on all instances, there maybe some further improvements that I would like to suggest if it is doable:- 
1) Currently urls are in plain text, so maybe they could be formated as hyperlinks so urls are 'clickable'?
2) Video Time Stamps which are sometimes added in the Video Description to directly go to the defined time of the video are also in plain text, so maybe also make them 'clickable' to go to the right section.
Though I am not sure how this could be programatically achievable in the context of a UserScript format.   
Anyway, the currently is big step compared to what we were missing before in any case with Youtube's changes.

**Comment by LennyPenny** [comment]
I'm hereby offering a 5€ bounty via paypal to anyone who gets this fixed in master! (send me a message from a mastodon account or email linked in your github profile linked to the commit after)

**Comment by 99thim** [comment]
1. gardockt: Totally understand
2. Same as LennyPenny, happy to offer $5 too to have this fixed. Would pay with bitcoin

**Comment by Trit34** [comment]
@gardockt It works! Thank you!

I just had to add a match line for my favorite instance (`// @match        *://invidious.fdn.fr/*`).

**Comment by unixfox** [comment]
While I really like the dedication from the community for willing to offer donations towards fixing this issue, I would prefer to keep it on topic in order to help the developers to easily and quickly gather the information needed to fix this issue.

If you want to give another bounty, please contact me on these official invidious channels, and I'll add your bounty on the very first comment:
- matrix: https://matrix.to/#/#invidious:matrix.org
- IRC: https://web.libera.chat/?channel=#invidious
- email: https://invidious.io/contact/

**Comment by techmetx11** [comment]
#3701 should fix this

**Comment by 99thim** [comment]
Did this really solved this? I dont see any difference?

**Comment by precondition** [comment]
> Did this really solved this? I dont see any difference?

What's the version shown at the bottom of the instance you're using? The fix has been merged less than a hour ago. Not all instances update that quickly.

**Comment by 99thim** [comment]
Ah yes your are correct, version used  2023.04.01-8db2a938.

**Comment by Trit34** [comment]
My favorite instance is updated every Sunday, so I’ll wait a bit before I can remove the user-script proposed by @gardockt.

Thank you, @techmetx11 and @SamantazFox! o/

**Comment by MintMain21** [comment]
I've noticed that on instances where the bug has been resolved, the userscript seemingly does nothing, so there's no harm in keeping it installed until you feel it's truly unnecessary.

**Comment by UltraBlackLinux** [comment]
Still experiencing this on 2023.08.26-ac0c060 https://vid.puffyan.us

**Comment by unixfox** [comment]
> Still experiencing this on 2023.08.26-ac0c060 [vid.puffyan.us](https://vid.puffyan.us)

which video ID?

**Comment by UltraBlackLinux** [comment]
I was about to tell you that this is any video, and then noticed that ublock origin out of all things is causing this. Some filterlist must be broken. 

Sorry for necrobumping.

**Comment by unixfox** [comment]
Please give the full URL. Can't replicate the issue for the moment.
