### ISSUE TITLE
[Bug] Nil assertion failed in RSS feeds

### ISSUE THREAD

**Issue by 9948aa9a** [iv-org/invidious#3795]
**Describe the bug**
Whenever I try to access to a RSS feed, the following error happens:
Nil assertion failed (NilAssertionError)

**Steps to Reproduce**
1. Go to a channel
2. Click on the RSS icon
3. There you have the error

**Logs**
Title: `Nil assertion failed (NilAssertionError)`
Date: `2023-05-09T17:09:11Z`
Route: `/feed/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw`
Version: `2023.05.08-10fee9da @ master`
   
```
Nil assertion failed (NilAssertionError)
  from /usr/lib/crystal/nil.cr:113:7 in 'not_nil!'
  from /usr/lib/crystal/nil.cr:109:3 in 'not_nil!'
  from src/invidious/routes/feeds.cr:166:15 in 'rss_channel'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/request_processor.cr:51:11 in 'process'
  from /usr/lib/crystal/http/server.cr:502:5 in '->'
  from /usr/lib/crystal/fiber.cr:146:11 in 'run'
  from ???
```

**Comment by unixfox** [comment]
Which instance are you using?

**Comment by 9948aa9a** [comment]
> Which instance are you using?

I'm using my own instance installed on my computer. That's been happening to me for 2-3 weeks (I update once a week).

**Comment by SamantazFox** [comment]
Fixed by #3793. Feel free to reopen if you continue to encounter the problem after updating!

**Comment by 9948aa9a** [comment]
Indeed, the issue with the RSS feed happened just when #3793 appeared, and I thought that was going to solve the issue with RSS as well. However, the problem continues, and I don't know why since apparently some other updated instances have it already working.

I'm running the following version:
 2023.05.08-10fee9da

**Comment by Fijxu** [comment]
Not fixed.

At commit 3a54e95

Crystal 1.8.2:

```
Title: `Nil assertion failed (NilAssertionError)`
Date: `2023-05-17T05:55:09Z`
Route: `/feed/channel/UC_t7gDUmMKexWoAl3CTWd5g`
Version: `2023.05.14-3a54e955 @ master`

<details>
<summary>Backtrace</summary>
<p>


Nil assertion failed (NilAssertionError)
  from /usr/lib/crystal/nil.cr:113:7 in 'not_nil!'
  from /usr/lib/crystal/nil.cr:109:3 in 'not_nil!'
  from src/invidious/routes/feeds.cr:166:15 in 'rss_channel'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/lib/crystal/fiber.cr:146:11 in 'run'
  from ???
</p>
</details>
```

It also happens with Crystal 1.7.3 and 1.6.2. Arch Linux. I need to delete some "player dependencies"?
