### ISSUE TITLE
When trying to login with Google: "Account has temporarily been disabled"

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#755]
I'm trying to login with my Google account but after entering my credentials I get this error message: `Account has temporarily been disabled`.

Why is my Google account not working on invidio.us?

**Comment by omarroth** [comment]
Are you able to login using Google's website?

**Comment by unixfox** [comment]
Yes I am.

**Comment by unixfox** [comment]
I just tested with my other Google account and I can reproduce the same bug (my second Google account has 2FA enabled too).

**Comment by Architector4** [comment]
Experiencing the same issue. I have 2FA enabled too.

I've also tried "App password" feature: https://myaccount.google.com/apppasswords

The password given from that feature should work with the account without 2FA checking or absolutely anything, yet trying to use it with Invidious yields the same "temporarily disabled" message.

**Comment by SugoiSheep** [comment]
I too have the same issue, except I do not have 2FA enabled. I am able to login to google without any issue.

**Comment by Beapal** [comment]
I am just trying to log in with Google account and get the same issue.

**I hope the contributors get this issue solved in no time.**

_P.S. is it possible to comment with Google account from invidious ?_

**Comment by Alamantus** [comment]
I just wanted to hop in and say I am experiencing the same issue when trying to log in with my Google account.

**Comment by MrBananaxx** [comment]
I have the same issue unfortunately and I have 2FA enabled.

**Comment by Hypario** [comment]
I have the same issue, i have 2FA enabled too

**Comment by omarroth** [comment]
I've pushed 0cf187dee73ede397c1ef67a61133d9736738fd5 which may help with this issue. 

Unfortunately I'm not able to reproduce this issue, testing with accounts with Authenticator, SMS, or none as the primary 2FA.

> I've also tried "App password" feature: https://myaccount.google.com/apppasswords

App passwords are currently unsupported. I would be very happy to have any information on how they could be implemented, although AFAIK it requires the app to register in Google, which is to be avoided for this project.

> is it possible to comment with Google account from invidious ?

It is not currently possible.

**Comment by Alamantus** [comment]
I'm still unable to log in with any of my Google accounts. It doesn't provide any further error messaging beyond what has already been said, even in the developer console and network tab...

Is there anything I can do to help you test? I can reproduce it consistently.

**Comment by Hypario** [comment]
Well, it seems that no matter what the password is for an account, the same error occur, "Account has temporarily been disabled".
Whenever i'm using a false account, i'm getting a weird error :
```
Expected Array for #[]?(index : Int), not Int64
Traceback:
Getting lookup...done, returned 200.
Getting challenge...done, returned 400.
```

**Comment by rex4539** [comment]
Same issue here with 2FA enabled.

**Comment by unixfox** [comment]
I even tried with [less secure apps](https://support.google.com/accounts/answer/6010255?hl=en), disabled 2FA and installed Invidious on my own VPS but it still doesn't work.

**Comment by vinibali** [comment]
I had the same days ago without 2FA and now with 2FA as well.
If I could select the correct numbers on my phone, it asks for a Google verification later. But no email, message or popup is in place what I could use...

**Comment by danieljo12** [comment]
Im also having this issue.... I have 2fa disabled... ScreenShot: https://imgur.com/ELrGQUA

**Comment by rendeko** [comment]
Issue still occurs for me as well.

**Comment by rex4539** [comment]
Today I managed to log in with Google successfully.

**Comment by unixfox** [comment]
Wow. You are right @rex4539! It worked...

**Comment by rex4539** [comment]
I would argue that this bug should closed because the actual bug of logging in with a Google account has been fixed.

A new feature request should be opened for the automatic subscriptions import.

**Comment by unixfox** [comment]
Better waiting a few days before closing it because we don't know if it will temporary work or stay like this *permanently*.

**Comment by Hypario** [comment]
It seems now the bug is fixed (not saying it is disabled), but i have another weird error that I talked about higher and specified at #754 which makes me unable to log in with google

**Comment by bugs181** [comment]
> It seems now the bug is fixed, at least for me (no error saying that my account has temporarily been disabled), but i have another weird error that I talked about higher and specified at #754 which makes me unable to log in with google

I too am getting the error from #754. I have 2FA enabled.

For clarity, here is the error again:

```
Expected Array for #[]?(index : Int), not Int64
Traceback:
Getting lookup...done, returned 200.
Getting challenge...done, returned 400.
```

**Comment by syeopite** [comment]
Bump. This is still an issue.
